#pragma once

/*
 * chat_html.h - 内嵌 HTML 聊天页面（含设置面板 + 模型预设）
 * 编译时嵌入，无需外部文件。
 */

static const char s_chat_html[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>K230Claw</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:-apple-system,sans-serif;background:#1a1a2e;color:#e0e0e0;height:100vh;display:flex;flex-direction:column}"
"#header{background:#16213e;padding:12px 20px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #0f3460}"
"#header .title{font-size:18px;font-weight:bold;color:#0f3460}"
"#header .title span{color:#e94560}"
".hdr-right{display:flex;align-items:center;gap:8px}"
"#model-tag{font-size:11px;color:#888;max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
"#gear{background:none;border:none;color:#888;font-size:20px;cursor:pointer;padding:4px 8px}"
"#gear:hover{color:#e94560}"
"#chat{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:8px}"
".msg{max-width:80%;padding:10px 14px;border-radius:12px;line-height:1.5;word-wrap:break-word;white-space:pre-wrap}"
".msg.user{align-self:flex-end;background:#0f3460;color:#fff}"
".msg.assistant{align-self:flex-start;background:#16213e;color:#e0e0e0;border:1px solid #333}"
".msg.system{align-self:center;color:#888;font-size:12px;background:transparent}"
"#input-area{display:flex;padding:12px;gap:8px;background:#16213e;border-top:1px solid #0f3460}"
"#input{flex:1;padding:10px 14px;border:1px solid #333;border-radius:20px;background:#1a1a2e;color:#e0e0e0;font-size:14px;outline:none}"
"#input:focus{border-color:#e94560}"
"#send{padding:10px 20px;background:#e94560;color:#fff;border:none;border-radius:20px;cursor:pointer;font-size:14px}"
"#send:hover{background:#c73e54}"
"#status{font-size:11px;color:#888}"
/* 设置面板 */
"#settings-overlay{display:none;position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.5);z-index:100}"
"#settings{display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#16213e;border:1px solid #0f3460;border-radius:12px;padding:24px;width:92%;max-width:460px;max-height:85vh;overflow-y:auto;z-index:101}"
"#settings h2{color:#e94560;margin-bottom:16px;font-size:16px}"
".tab-bar{display:flex;gap:0;margin-bottom:16px;border-bottom:1px solid #333}"
".tab-bar button{flex:1;padding:8px;background:none;border:none;border-bottom:2px solid transparent;color:#888;cursor:pointer;font-size:13px}"
".tab-bar button.active{color:#e94560;border-bottom-color:#e94560}"
".tab-panel{display:none}"
".tab-panel.active{display:block}"
"#settings label{display:block;color:#aaa;font-size:12px;margin:10px 0 4px}"
"#settings select,#settings input[type=text],#settings input[type=password]{"
  "width:100%;padding:8px 12px;border:1px solid #333;border-radius:8px;"
  "background:#1a1a2e;color:#e0e0e0;font-size:13px;outline:none}"
"#settings select:focus,#settings input:focus{border-color:#e94560}"
".btn-row{display:flex;gap:8px;margin-top:18px;justify-content:flex-end}"
".btn{padding:8px 18px;border:none;border-radius:8px;cursor:pointer;font-size:13px}"
".btn-save{background:#e94560;color:#fff}"
".btn-save:hover{background:#c73e54}"
".btn-cancel{background:#333;color:#ccc}"
".btn-cancel:hover{background:#444}"
/* 预设卡片 */
".preset-list{display:flex;flex-direction:column;gap:8px;margin-top:8px}"
".preset-card{display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:#1a1a2e;border:1px solid #333;border-radius:8px;cursor:pointer}"
".preset-card:hover{border-color:#e94560}"
".preset-card.active{border-color:#4caf50;background:#1a2a1e}"
".preset-info{flex:1;min-width:0}"
".preset-name{font-size:14px;font-weight:bold;color:#e0e0e0}"
".preset-detail{font-size:11px;color:#888;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
".preset-actions{display:flex;gap:4px;flex-shrink:0}"
".preset-actions button{background:none;border:none;color:#888;font-size:16px;cursor:pointer;padding:2px 6px}"
".preset-actions button:hover{color:#e94560}"
".preset-add{display:flex;align-items:center;justify-content:center;padding:10px;background:transparent;border:1px dashed #555;border-radius:8px;color:#888;cursor:pointer;font-size:13px}"
".preset-add:hover{border-color:#e94560;color:#e94560}"
/* 预设编辑 */
"#preset-edit{display:none;margin-top:12px;padding:12px;background:#1a1a2e;border:1px solid #333;border-radius:8px}"
"#preset-edit h3{color:#e94560;font-size:14px;margin-bottom:8px}"
"#toast{display:none;position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#4caf50;color:#fff;padding:8px 20px;border-radius:8px;font-size:13px;z-index:200}"
"</style>"
"</head>"
"<body>"
"<div id=\"header\">"
  "<div class=\"title\"><span>K230</span>Claw</div>"
  "<div class=\"hdr-right\">"
    "<span id=\"model-tag\"></span>"
    "<span id=\"status\">Connecting...</span>"
    "<button id=\"gear\" title=\"Settings\">&#9881;</button>"
  "</div>"
"</div>"
"<div id=\"chat\"></div>"
"<div id=\"input-area\">"
  "<input id=\"input\" placeholder=\"Type a message...\" autocomplete=\"off\">"
  "<button id=\"send\">Send</button>"
"</div>"
"<div id=\"toast\"></div>"
"<div id=\"settings-overlay\"></div>"
"<div id=\"settings\">"
  "<h2>Settings</h2>"
  "<div class=\"tab-bar\">"
    "<button class=\"active\" data-tab=\"presets\">Presets</button>"
    "<button data-tab=\"advanced\">Advanced</button>"
  "</div>"

  /* 预设 Tab */
  "<div class=\"tab-panel active\" id=\"tab-presets\">"
    "<div class=\"preset-list\" id=\"preset-list\"></div>"
    "<div class=\"preset-add\" id=\"preset-add\">+ Add Preset</div>"
    "<div id=\"preset-edit\">"
      "<h3 id=\"pe-title\">New Preset</h3>"
      "<label>Name</label>"
      "<input type=\"text\" id=\"pe-name\" placeholder=\"DeepSeek\">"
      "<label>Provider</label>"
      "<select id=\"pe-provider\">"
        "<option value=\"openai\">OpenAI (compatible)</option>"
        "<option value=\"anthropic\">Anthropic</option>"
      "</select>"
      "<label>Model</label>"
      "<input type=\"text\" id=\"pe-model\" placeholder=\"deepseek-chat\">"
      "<label>API Key</label>"
      "<input type=\"password\" id=\"pe-key\" placeholder=\"sk-...\">"
      "<label>API URL</label>"
      "<input type=\"text\" id=\"pe-url\" placeholder=\"https://api.deepseek.com/v1/chat/completions\">"
      "<div class=\"btn-row\">"
        "<button class=\"btn btn-cancel\" id=\"pe-cancel\">Cancel</button>"
        "<button class=\"btn btn-save\" id=\"pe-save\">Save Preset</button>"
      "</div>"
    "</div>"
  "</div>"

  /* 高级 Tab */
  "<div class=\"tab-panel\" id=\"tab-advanced\">"
    "<label>Provider</label>"
    "<select id=\"s-provider\">"
      "<option value=\"openai\">OpenAI</option>"
      "<option value=\"anthropic\">Anthropic</option>"
    "</select>"
    "<label>Model</label>"
    "<input type=\"text\" id=\"s-model\" placeholder=\"gpt-4o\">"
    "<label id=\"l-key\">API Key</label>"
    "<input type=\"password\" id=\"s-key\" placeholder=\"sk-...\">"
    "<label id=\"l-url\">API URL</label>"
    "<input type=\"text\" id=\"s-url\">"
    "<label>Proxy</label>"
    "<input type=\"text\" id=\"s-proxy\" placeholder=\"http://127.0.0.1:7890\">"
    "<div class=\"btn-row\">"
      "<button class=\"btn btn-cancel\" id=\"s-cancel\">Cancel</button>"
      "<button class=\"btn btn-save\" id=\"s-save\">Save</button>"
    "</div>"
  "</div>"
"</div>"

"<script>"
"const chat=document.getElementById('chat');"
"const input=document.getElementById('input');"
"const sendBtn=document.getElementById('send');"
"const status=document.getElementById('status');"
"const modelTag=document.getElementById('model-tag');"
"const gear=document.getElementById('gear');"
"const overlay=document.getElementById('settings-overlay');"
"const panel=document.getElementById('settings');"
"const toast=document.getElementById('toast');"
"let ws,cfgData={},editIdx=-1;"

/* WebSocket */
"function connect(){"
  "const proto=location.protocol==='https:'?'wss:':'ws:';"
  "ws=new WebSocket(proto+'//'+location.host+'/ws');"
  "ws.onopen=()=>{"
    "status.textContent='Connected';"
    "status.style.color='#4caf50';"
    "addMsg('system','Connected to K230Claw.');"
    "ws.send(JSON.stringify({type:'get_config'}));"
  "};"
  "ws.onclose=()=>{"
    "status.textContent='Disconnected';"
    "status.style.color='#f44336';"
    "addMsg('system','Disconnected. Reconnecting...');"
    "setTimeout(connect,3000);"
  "};"
  "ws.onerror=()=>{ws.close()};"
  "ws.onmessage=(e)=>{"
    "try{"
      "const d=JSON.parse(e.data);"
      "if(d.type==='config'){"
        "cfgData=d.data;"
        "updateModelTag();"
        "if(panel.style.display==='block'){fillSettings();renderPresets()}"
      "}else if(d.type==='config_saved'){"
        "showToast('Settings saved');"
        "closeSettings();"
        "ws.send(JSON.stringify({type:'get_config'}));"
      "}else if(d.type==='preset_applied'){"
        "showToast('Preset applied');"
        "closeSettings();"
        "ws.send(JSON.stringify({type:'get_config'}));"
      "}else if(d.type==='presets_saved'){"
        "showToast('Presets saved');"
        "ws.send(JSON.stringify({type:'get_config'}));"
      "}else if(d.type==='config_error'){"
        "showToast('Error: '+(d.message||'unknown'),'#f44336');"
      "}else if(d.type==='clear_screen'){"
        "chat.innerHTML='';"
        "showToast('Screen cleared');"
      "}else if(d.text){"
        "addMsg('assistant',d.text);"
      "}"
    "}catch(x){addMsg('assistant',e.data)}"
  "};"
"}"

"function updateModelTag(){"
  "if(cfgData.model)modelTag.textContent=cfgData.model;"
"}"

/* 对话 */
"function addMsg(role,text){"
  "removeTyping();"
  "const d=document.createElement('div');"
  "d.className='msg '+role;"
  "d.textContent=text;"
  "chat.appendChild(d);"
  "chat.scrollTop=chat.scrollHeight;"
"}"
"function showTyping(){"
  "removeTyping();"
  "const d=document.createElement('div');"
  "d.className='msg assistant';"
  "d.id='typing-indicator';"
  "d.textContent='Thinking...';"
  "d.style.opacity='0.5';"
  "chat.appendChild(d);"
  "chat.scrollTop=chat.scrollHeight;"
"}"
"function removeTyping(){"
  "const t=document.getElementById('typing-indicator');"
  "if(t)t.remove();"
"}"
"function send(){"
  "const t=input.value.trim();"
  "if(!t||!ws||ws.readyState!==1)return;"
  "addMsg('user',t);"
  "ws.send(JSON.stringify({text:t}));"
  "input.value='';"
  "if(t[0]!=='/')showTyping();"
"}"
"sendBtn.onclick=send;"
"input.onkeydown=(e)=>{if(e.key==='Enter')send()};"

/* 设置面板 */
"function openSettings(){"
  "if(ws&&ws.readyState===1)ws.send(JSON.stringify({type:'get_config'}));"
  "overlay.style.display='block';"
  "panel.style.display='block';"
  "fillSettings();"
  "renderPresets();"
  "hidePresetEdit();"
"}"
"function closeSettings(){"
  "overlay.style.display='none';"
  "panel.style.display='none';"
"}"

/* Tab 切换 */
"document.querySelectorAll('.tab-bar button').forEach(btn=>{"
  "btn.onclick=()=>{"
    "document.querySelectorAll('.tab-bar button').forEach(b=>b.classList.remove('active'));"
    "document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));"
    "btn.classList.add('active');"
    "document.getElementById('tab-'+btn.dataset.tab).classList.add('active');"
  "};"
"});"

/* 高级设置 */
"function fillSettings(){"
  "document.getElementById('s-provider').value=cfgData.provider||'openai';"
  "document.getElementById('s-model').value=cfgData.model||'';"
  "updateKeyLabels();"
  "document.getElementById('s-proxy').value=cfgData.proxy||'';"
"}"
"function updateKeyLabels(){"
  "const pv=document.getElementById('s-provider').value;"
  "const lk=document.getElementById('l-key');"
  "const lu=document.getElementById('l-url');"
  "const sk=document.getElementById('s-key');"
  "const su=document.getElementById('s-url');"
  "if(pv==='anthropic'){"
    "lk.textContent='Anthropic API Key';"
    "lu.textContent='Anthropic API URL';"
    "sk.value=cfgData.anthropic_api_key||'';"
    "su.value=cfgData.anthropic_api_url||'';"
  "}else{"
    "lk.textContent='OpenAI API Key';"
    "lu.textContent='OpenAI API URL';"
    "sk.value=cfgData.openai_api_key||'';"
    "su.value=cfgData.openai_api_url||'';"
  "}"
"}"
"function saveAdvanced(){"
  "const pv=document.getElementById('s-provider').value;"
  "const d={provider:pv,model:document.getElementById('s-model').value,"
    "proxy:document.getElementById('s-proxy').value};"
  "const key=document.getElementById('s-key').value;"
  "const url=document.getElementById('s-url').value;"
  "if(pv==='anthropic'){"
    "d.anthropic_api_key=key;d.anthropic_api_url=url;"
    "d.openai_api_key=cfgData.openai_api_key||'';d.openai_api_url=cfgData.openai_api_url||'';"
  "}else{"
    "d.openai_api_key=key;d.openai_api_url=url;"
    "d.anthropic_api_key=cfgData.anthropic_api_key||'';d.anthropic_api_url=cfgData.anthropic_api_url||'';"
  "}"
  "if(ws&&ws.readyState===1)ws.send(JSON.stringify({type:'set_config',data:d}));"
"}"
"document.getElementById('s-provider').onchange=updateKeyLabels;"
"document.getElementById('s-save').onclick=saveAdvanced;"
"document.getElementById('s-cancel').onclick=closeSettings;"

/* 预设管理 */
"function getPresets(){return cfgData.model_list||[]}"

"function renderPresets(){"
  "const list=document.getElementById('preset-list');"
  "const presets=getPresets();"
  "list.innerHTML='';"
  "presets.forEach((p,i)=>{"
    "const isActive=(p.provider===cfgData.provider&&p.model===cfgData.model);"
    "const card=document.createElement('div');"
    "card.className='preset-card'+(isActive?' active':'');"
    "card.innerHTML="
      "'<div class=\"preset-info\">"
        "<div class=\"preset-name\">'+(p.name||p.model)+'</div>"
        "<div class=\"preset-detail\">'+(p.provider||'')+' / '+(p.model||'')+'</div>"
      "</div>"
      "<div class=\"preset-actions\">"
        "<button title=\"Edit\" data-edit=\"'+i+'\">&#9998;</button>"
        "<button title=\"Delete\" data-del=\"'+i+'\">&times;</button>"
      "</div>';"
    "card.querySelector('.preset-info').onclick=()=>applyPreset(i);"
    "card.querySelector('[data-edit]').onclick=(e)=>{e.stopPropagation();editPreset(i)};"
    "card.querySelector('[data-del]').onclick=(e)=>{e.stopPropagation();deletePreset(i)};"
    "list.appendChild(card);"
  "});"
"}"

"function applyPreset(i){"
  "if(ws&&ws.readyState===1)"
    "ws.send(JSON.stringify({type:'apply_preset',data:{index:i}}));"
"}"

"function deletePreset(i){"
  "const presets=getPresets().slice();"
  "presets.splice(i,1);"
  "if(ws&&ws.readyState===1)"
    "ws.send(JSON.stringify({type:'save_presets',data:presets}));"
"}"

/* 预设编辑表单 */
"function showPresetEdit(){"
  "document.getElementById('preset-edit').style.display='block';"
"}"
"function hidePresetEdit(){"
  "document.getElementById('preset-edit').style.display='none';"
  "editIdx=-1;"
"}"

"document.getElementById('preset-add').onclick=()=>{"
  "editIdx=-1;"
  "document.getElementById('pe-title').textContent='New Preset';"
  "document.getElementById('pe-name').value='';"
  "document.getElementById('pe-provider').value='openai';"
  "document.getElementById('pe-model').value='';"
  "document.getElementById('pe-key').value='';"
  "document.getElementById('pe-url').value='';"
  "showPresetEdit();"
"};"

"function editPreset(i){"
  "const p=getPresets()[i];"
  "if(!p)return;"
  "editIdx=i;"
  "document.getElementById('pe-title').textContent='Edit Preset';"
  "document.getElementById('pe-name').value=p.name||'';"
  "document.getElementById('pe-provider').value=p.provider||'openai';"
  "document.getElementById('pe-model').value=p.model||'';"
  "document.getElementById('pe-key').value=p.api_key||'';"
  "document.getElementById('pe-url').value=p.api_url||'';"
  "showPresetEdit();"
"}"

"document.getElementById('pe-save').onclick=()=>{"
  "const p={"
    "name:document.getElementById('pe-name').value.trim(),"
    "provider:document.getElementById('pe-provider').value,"
    "model:document.getElementById('pe-model').value.trim(),"
    "api_key:document.getElementById('pe-key').value.trim(),"
    "api_url:document.getElementById('pe-url').value.trim()"
  "};"
  "if(!p.model){showToast('Model is required','#f44336');return}"
  "if(!p.name)p.name=p.model;"
  "const presets=getPresets().slice();"
  "if(editIdx>=0&&editIdx<presets.length){presets[editIdx]=p}else{presets.push(p)}"
  "if(ws&&ws.readyState===1)"
    "ws.send(JSON.stringify({type:'save_presets',data:presets}));"
  "hidePresetEdit();"
"};"
"document.getElementById('pe-cancel').onclick=hidePresetEdit;"

/* Toast */
"function showToast(msg,bg){"
  "toast.textContent=msg;"
  "toast.style.background=bg||'#4caf50';"
  "toast.style.display='block';"
  "setTimeout(()=>{toast.style.display='none'},2000);"
"}"

"gear.onclick=openSettings;"
"overlay.onclick=closeSettings;"

"connect();"
"</script>"
"</body>"
"</html>";
