/*
 * stream_html.h - 流媒体监控页面
 *
 * MJPEG 实时视频 + YOLOv8 多目标检测叠加 + 状态栏。
 * 访问路径: /stream.html
 */

static const char s_stream_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>K230Claw - Navigator</title>\n"
"<style>\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{background:#0d1117;color:#c9d1d9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;min-height:100vh;display:flex;flex-direction:column;align-items:center;padding:20px}\n"
".header{width:100%;max-width:680px;display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}\n"
"h1{font-size:20px;color:#58a6ff}\n"
"h1 span{font-size:13px;color:#8b949e;font-weight:normal;margin-left:8px}\n"
".nav a{color:#58a6ff;text-decoration:none;font-size:14px}\n"
".nav a:hover{text-decoration:underline}\n"
"#stream{width:640px;max-width:100%;border:2px solid #30363d;border-radius:8px;background:#161b22;min-height:480px}\n"
".status{width:640px;max-width:100%;margin-top:12px;padding:12px 16px;background:#161b22;border:1px solid #30363d;border-radius:8px;display:flex;justify-content:space-between;font-size:13px;color:#8b949e}\n"
".status .det-count{color:#d2a8ff}\n"
".status .top-class{color:#3fb950;font-weight:bold}\n"
".status .fps{color:#79c0ff}\n"
".error{color:#f85149;text-align:center;padding:40px;font-size:16px}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class='header'>\n"
"  <h1>K230Claw Navigator <span id='fps-val'>--</span></h1>\n"
"  <div class='nav'><a href='/'>Chat</a></div>\n"
"</div>\n"
"<img id='stream' src='/stream' onerror='showError()'>\n"
"<div id='error' class='error' style='display:none'>Video stream unavailable. Make sure navigator role is active.</div>\n"
"<div class='status'>\n"
"  <span class='det-count' id='det-info'>Objects: --</span>\n"
"  <span class='top-class' id='top-info'>Top: --</span>\n"
"  <span class='fps' id='fps-info'>FPS: --</span>\n"
"</div>\n"
"<script>\n"
"function showError(){\n"
"  document.getElementById('stream').style.display='none';\n"
"  document.getElementById('error').style.display='block';\n"
"}\n"
"function updateStatus(){\n"
"  fetch('/stream_status').then(function(r){return r.json()}).then(function(d){\n"
"    document.getElementById('det-info').textContent='Objects: '+d.detections;\n"
"    var ti=document.getElementById('top-info');\n"
"    if(d.top_class){ti.textContent='Top: '+d.top_class}\n"
"    else{ti.textContent='Top: --'}\n"
"    document.getElementById('fps-info').textContent='FPS: '+d.fps.toFixed(1);\n"
"    document.getElementById('fps-val').textContent=d.fps.toFixed(1)+' fps';\n"
"  }).catch(function(){});\n"
"}\n"
"setInterval(updateStatus,2000);\n"
"updateStatus();\n"
"</script>\n"
"</body>\n"
"</html>\n";
